name: GitHubRelease
on:
  # Trigger the workflow on pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Zip Folder
      run: zip -r ocular-d.zip ocular-d

